### ISSUE TITLE
Does this module calculate business day only and ignore hour/minute/second?

### ISSUE THREAD

**Issue by pintubigfoot** [gnaneshwar441/Business_Duration#9]
Hi @gnaneshwar441,

Following Example 1 provided by README.md, it doesn't seem to giving correct seconds, minutes, and hours.

Can you please advice?

```
>>> start_date = pd.to_datetime('2017-07-01 02:02:00')
>>> biz_open_time=time(7,0,0)
>>> biz_close_time=time(17,0,0)
>>> end_date = pd.to_datetime('2017-07-06 04:48:10')
>>> print(businessDuration(startdate=start_date,enddate=end_date,starttime=biz_open_time,endtime=biz_close_time,unit='min'))
1800.0
>>> print(businessDuration(startdate=start_date,enddate=end_date,starttime=biz_open_time,endtime=biz_close_time,unit='sec'))
108000         (okay, let's assume 108000 seconds is correct when the end_date time above is '2017-07-06 04:48:10'
>>> end_date = pd.to_datetime('2017-07-06 04:48:20')
>>> print(businessDuration(startdate=start_date,enddate=end_date,starttime=biz_open_time,endtime=biz_close_time,unit='sec'))
108000         (why is the output still the same as previous one when end_date time above has different number in second?)
>>> end_date = pd.to_datetime('2017-07-06 04:49:20')
>>> print(businessDuration(startdate=start_date,enddate=end_date,starttime=biz_open_time,endtime=biz_close_time,unit='sec'))
108000         (why is the output still the same as previous one when end_date time above has different number in minute?)
>>> end_date = pd.to_datetime('2017-07-06 05:49:20')
>>> print(businessDuration(startdate=start_date,enddate=end_date,starttime=biz_open_time,endtime=biz_close_time,unit='sec'))
108000         (why is the output still the same as previous one when end_date time above has different number in hour?)
```

Thank you

**Comment by gnaneshwar441** [comment]
Hello,

The output is showing 108000 seconds = 1800 minutes because

2017-07-01 & 02 - weekends (excluded from calculation)
2017-07-03 to 05 - 3 working days
2017-07-06 - excluded from calculation because end_date's time < biz_open_time (7,0,0)
Since biz timings is between (7.0,0) and (17,0,0) for 3 days = 10 hours X 3 days = 30 Hrs = 1800 mins = 108000 seconds

Hope this helps

**Comment by gnaneshwar441** [comment]
Hello,

The output is showing 108000 seconds = 1800 minutes because

2017-07-01 & 02 - weekends (excluded from calculation)
*2017-07-03 to 05 - 3 working days*
2017-07-06 - excluded from calculation because end_date's time <
biz_open_time (7,0,0)
Since biz timings is between (7.0,0) and (17,0,0) for 3 days = 10 hours X 3
days = 30 Hrs = 1800 mins = 108000 seconds

Hope this helps
